{"name": "test_create_user_with_invalid_values_002", "status": "passed", "description": "create_user_with_invalid_values", "start": 1662025910335, "stop": 1662025917304, "uuid": "30122938-5947-4f64-a083-e6ac1f009496", "historyId": "aa5d150ce42e2398a1ade11625555ecd", "testCaseId": "7fbb83514f4b26defe89cb9ec0ae36bc", "fullName": "Test_case.Test_Create_User_API#test_create_user_with_invalid_values_002", "labels": [{"name": "severity", "value": "Critical"}, {"name": "parentSuite", "value": "Test_case"}, {"name": "suite", "value": "Test_Create_User_API"}, {"name": "host", "value": "DESKTOP-KBHEFTS"}, {"name": "thread", "value": "22096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_case.Test_Create_User_API"}]}